language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10

install:
  - pip install --download-cache=".pip_download_cache" -q Django==$DJANGO_VERSION
  - pip install --download-cache=".pip_download_cache" -r requirements.txt
  - python setup.py -q install

script: coverage run setup.py test