language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10

install:
  - pip install -q -r requirements.txt
  - pip install -q --upgrade Django==$DJANGO_VERSION
  - python setup.py -q install

script: coverage run --source=django_rest_model setup.py test

after_success:
  coveralls